---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog


