---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog
---
spring:
  profiles: sentence
