---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog


